return {
    language = "auto",
    show_ante = true,
    show_round = true,
    show_blind = true,
    show_hands = true,
    show_discards = true,
    show_money = false,
    show_deck = false,
    show_stake = false,
    show_challenge = true,
    show_blind_progress = false,
    show_hand_type = true,
    show_score = false,
    show_elapsed = false,
    show_button = false,
    carousel = false,
    carousel_interval = 3,
    carousel_pages = {"progress", "blind", "money", "deck", "hand"},
    update_interval = 1.0,
}
